import {useEffect,useState} from 'react';
import './accounts.css';

async function request(path:string,options:RequestInit={}){const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});if(!r.ok){let message='Service indisponible';try{const d=await r.json();message=typeof d.detail==='string'?d.detail:'Vérifie les informations saisies.';}catch{}throw new Error(message);}return r.json();}
export function Registration({inviteKey,onReady}:{inviteKey:string;onReady:()=>Promise<void>}){
 const [name,setName]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[key,setKey]=useState(''),[copied,setCopied]=useState(false);
 return <main className="login"><section className="login-card account-registration"><span className="eyebrow">TON ESPACE PERSONNEL</span><h1>{key?'Ton compte est créé':'Bienvenue dans Coach AI'}</h1>{key?<><p>Conserve cette clé personnelle : elle te servira pour te reconnecter et transférer tes connexions Garmin et ChatGPT. Elle ne sera plus affichée après cette page.</p><label>Ta clé d’accès<input readOnly value={key} aria-label="Ta clé d’accès" onFocus={e=>e.target.select()}/></label><button className="outline" onClick={()=>void navigator.clipboard.writeText(key).then(()=>setCopied(true)).catch(()=>setError('Sélectionne la clé et copie-la manuellement.'))}>{copied?'Clé copiée':'Copier ma clé'}</button><button className="primary" onClick={()=>{history.replaceState(null,'',location.pathname+location.search);void onReady();}}>J’ai conservé ma clé · ouvrir mon espace</button></>:<><p>Crée ton compte privé, puis connecte ton Garmin et ton ChatGPT. Tes activités et tes discussions restent dans ton espace.</p><form onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void request('/register',{method:'POST',body:JSON.stringify({name:name.trim(),invite_key:inviteKey})}).then(value=>setKey(value.access_key)).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label>Ton prénom<input autoComplete="given-name" required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={busy||!name.trim()}>{busy?'Création…':'Créer mon compte et ma clé'}</button></form><p className="hint">Lien d’invitation valable 7 jours, utilisable une seule fois.</p><button className="text-button" onClick={()=>{history.replaceState(null,'',location.pathname+location.search);void onReady();}}>J’ai déjà un compte</button></>}{error&&<p className="error" role="alert">{error}</p>}</section></main>;
}
type Invitation={id:string;label:string;expires_at:number;used_at?:number};
export function Invitations(){
 const [items,setItems]=useState<Invitation[]>([]),[label,setLabel]=useState(''),[url,setUrl]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
 async function load(){const d=await request('/invitations');setItems(d.invitations);}
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 return <section className="card account-invitations"><h2>Inviter une personne</h2><p>Elle créera son compte avec sa propre clé, puis connectera ses comptes Garmin et ChatGPT.</p><form onSubmit={e=>{e.preventDefault();setBusy(true);setError('');void request('/invitations',{method:'POST',body:JSON.stringify({label})}).then(value=>{setUrl(location.origin+'/#invite='+encodeURIComponent(value.invite_key));setCopied(false);return load();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label>Nom de l’invitation<input maxLength={100} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Ex. Invitation famille"/></label><button className="primary" disabled={busy}>Créer un lien d’inscription</button></form>{url&&<div className="account-invite-link"><label>Lien privé · valable 7 jours<input readOnly value={url} onFocus={e=>e.target.select()}/></label><button className="outline" onClick={()=>void navigator.clipboard.writeText(url).then(()=>setCopied(true)).catch(()=>setError('Sélectionne le lien et copie-le manuellement.'))}>{copied?'Lien copié':'Copier le lien'}</button><small>Envoie ce lien à la personne. Il est affiché uniquement lors de sa création.</small></div>}{items.map(item=><div className="account-invite-row" key={item.id}><span>{item.label||'Invitation'}<small>{item.used_at?'Utilisée':item.expires_at*1000<Date.now()?'Expirée':'Expire le '+new Date(item.expires_at*1000).toLocaleDateString('fr-FR')}</small></span>{!item.used_at&&<button className="outline" disabled={busy} onClick={()=>{setBusy(true);setError('');void request('/invitations/'+item.id,{method:'DELETE'}).then(()=>{setUrl('');return load();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Annuler le lien</button>}</div>)}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
