import {useEffect,useState} from 'react';
import {Activity,Bike,Dumbbell,Waves,Footprints,Trophy,ArrowUpRight,ArrowLeft,Clock,Heart,RefreshCw} from 'lucide-react';
import './activities.css';
type Entry={key:string;data:Record<string,any>};
type Page={items:Entry[];total:number;totals:{duration:number|null;distance:number|null};page_size:number};
type Detail=Entry&{laps:Record<string,any>[];fetched_at:string|null};
async function request<T>(path:string,options:RequestInit={}):Promise<T>{const r=await fetch('/api'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});if(!r.ok){let message='Service indisponible';try{message=(await r.json()).detail||message;}catch{}throw new Error(message);}return r.json();}
const sports=[['','Tous les sports'],['running','Course'],['cycling','Vélo'],['strength','Musculation'],['tennis','Tennis'],['swimming','Natation'],['walking','Marche']];
function sportOf(a:Record<string,any>){const key=String(a.activityType?.typeKey||'').toLowerCase();return sports.slice(1).find(([s])=>key.includes(s)||(s==='cycling'&&key.includes('biking'))||(s==='strength'&&key.includes('fitness_equipment'))||(s==='walking'&&key.includes('hiking')))?.[0]||'other';}
function SportIcon({sport}:{sport:string}){const Icon=({running:Activity,cycling:Bike,strength:Dumbbell,tennis:Trophy,swimming:Waves,walking:Footprints} as Record<string,typeof Activity>)[sport]||Activity;return <Icon size={24}/>;}
const number=(v:number,d=0)=>v.toLocaleString('fr-FR',{maximumFractionDigits:d});
const duration=(v:number|null|undefined)=>v==null?'—':`${Math.floor(v/3600)?`${Math.floor(v/3600)} h `:''}${Math.floor(v%3600/60)} min`;
const distance=(v:number|null|undefined,s='')=>v==null?'—':s==='swimming'?`${number(v)} m`:`${number(v/1000,2)} km`;
function date(a:Record<string,any>){const raw=a.startTimeLocal||a.startTimeGMT;if(!raw)return 'Date indisponible';const d=new Date(String(raw).replace(' ','T'));return Number.isNaN(d.getTime())?String(raw):d.toLocaleDateString('fr-FR',{day:'numeric',month:'long',year:'numeric'});}
function metrics(a:Record<string,any>,sport:string){const speed=a.averageSpeed;const pace=speed>0?`${Math.floor(Math.round(1000/speed)/60)}:${String(Math.round(1000/speed)%60).padStart(2,'0')} /km`:null;const values:[string,string][]=[['Durée',duration(a.duration)],['Distance',distance(a.distance,sport)],['FC moyenne',a.averageHR==null?'—':`${number(a.averageHR)} bpm`],['FC maximale',a.maxHR==null?'—':`${number(a.maxHR)} bpm`],['Calories',a.calories==null?'—':`${number(a.calories)} kcal`]];
 if(['running','walking'].includes(sport))values.push(['Allure moyenne',pace||'—']);
 if(sport==='cycling')values.push(['Vitesse moyenne',speed==null?'—':`${number(speed*3.6,1)} km/h`],['Puissance moyenne',a.averagePower==null?'—':`${number(a.averagePower)} W`]);
 if(['running','cycling','walking'].includes(sport))values.push(['Dénivelé positif',a.elevationGain==null?'—':`${number(a.elevationGain)} m`]);
 for(const [key,label] of [['aerobicTrainingEffect','Effet aérobie'],['anaerobicTrainingEffect','Effet anaérobie']])if(a[key]!=null)values.push([label,number(a[key],1)]);
 return values;}
export function ActivitiesBoard({revision}:{revision:string}){
 const [page,setPage]=useState<Page|null>(null),[offset,setOffset]=useState(0),[sport,setSport]=useState(''),[query,setQuery]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState('');
 const [selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{let live=true;setLoading(true);setError('');const params=new URLSearchParams({offset:String(offset),sport,query});if(start)params.set('start',start);if(end)params.set('end',end);const timer=setTimeout(()=>{void request<Page>('/activities?'+params).then(p=>{if(live)setPage(p);}).catch(e=>{if(live)setError(e.message);}).finally(()=>{if(live)setLoading(false);});},200);return()=>{live=false;clearTimeout(timer);};},[offset,sport,query,start,end,revision]);
 function filter(fn:()=>void){fn();setOffset(0);}
 if(selected)return <ActivityDetail id={selected} onBack={()=>setSelected(null)}/>;
 return <div className="activity-board"><div className="activity-toolbar"><label>Rechercher<input placeholder="Nom d’une séance…" value={query} maxLength={200} onChange={e=>filter(()=>setQuery(e.target.value))}/></label><label>Depuis<input type="date" value={start} onChange={e=>filter(()=>setStart(e.target.value))}/></label><label>Jusqu’au<input type="date" value={end} onChange={e=>filter(()=>setEnd(e.target.value))}/></label></div><div className="activity-filters">{sports.map(([id,label])=><button className={sport===id?'selected':''} key={id} onClick={()=>filter(()=>setSport(id))}>{label}</button>)}</div>
 {error&&<p role="alert" className="error">{error}</p>}{page&&<div className="board-totals"><div><small>SÉANCES</small><strong>{number(page.total)}</strong></div><div><small>DURÉE TOTALE</small><strong>{duration(page.totals.duration)}</strong></div><div><small>DISTANCE TOTALE</small><strong>{distance(page.totals.distance,sport)}</strong></div></div>}
 {loading?<p aria-live="polite">Chargement des activités…</p>:page?.items.length?<div className="activity-cards">{page.items.map(({key,data:a})=>{const s=sportOf(a);return <button className={`sport-card sport-${s}`} key={key} onClick={()=>setSelected(key)}><div className="sport-card-top"><span className="sport-symbol"><SportIcon sport={s}/></span><span>{sports.find(([id])=>id===s)?.[1]||'Autre sport'}</span><ArrowUpRight size={18}/></div><h2>{a.activityName||'Activité Garmin'}</h2><p>{date(a)}</p><div className="sport-card-values"><span><Clock size={15}/>{duration(a.duration)}</span>{a.distance!=null&&<span>{distance(a.distance,s)}</span>}{a.averageHR!=null&&<span><Heart size={15}/>{number(a.averageHR)} bpm</span>}</div><div className="sport-card-footer">Voir la séance <ArrowUpRight size={15}/></div></button>;})}</div>:<div className="card activity-empty"><Activity size={32}/><h2>Aucune activité sur cette sélection</h2><p>Modifie les filtres ou synchronise Garmin depuis Connexions.</p></div>}
 {page&&<div className="history-pagination"><button className="outline" disabled={!offset||loading} onClick={()=>setOffset(Math.max(0,offset-24))}>Précédent</button><span>{page.total?`${offset+1}–${Math.min(offset+24,page.total)} sur ${page.total}`:'0 activité'}</span><button className="outline" disabled={offset+24>=page.total||loading} onClick={()=>setOffset(offset+24)}>Suivant</button></div>}</div>;
}
function ActivityDetail({id,onBack}:{id:string;onBack:()=>void}){
 const [detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;void request<Detail>('/activities/'+encodeURIComponent(id)).then(d=>{if(live)setDetail(d);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[id]);
 async function refresh(){setBusy(true);setError('');try{setDetail(await request<Detail>('/activities/'+encodeURIComponent(id)+'/refresh',{method:'POST'}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const a=detail?.data,s=a?sportOf(a):'other';
 return <div className="activity-detail"><button className="text-button" onClick={onBack}><ArrowLeft size={16}/>Toutes mes activités</button>{error&&<p className="error" role="alert">{error}</p>}{a?<><div className={`detail-hero sport-${s}`}><span className="sport-symbol"><SportIcon sport={s}/></span><div><span>{sports.find(([id])=>id===s)?.[1]||a.activityType?.typeKey||'Activité'}</span><h2>{a.activityName||'Séance Garmin'}</h2><p>{date(a)} · {String(a.startTimeLocal||a.startTimeGMT||'').slice(11,16)}{!a.startTimeLocal&&a.startTimeGMT?' UTC':''}</p></div></div><div className="detail-metrics">{metrics(a,s).map(([label,value])=><article className="card" key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><article className="card"><div className="section-title"><h2>Détails Garmin</h2><button className="outline" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>{busy?'Récupération…':detail?.fetched_at?'Actualiser les détails':'Récupérer les détails'}</button></div><p>Mesures et tours disponibles sur Garmin. Les valeurs absentes sont affichées « — ».</p>{detail?.fetched_at&&<small>Récupérés le {new Date(detail.fetched_at).toLocaleString('fr-FR')}</small>}{detail?.laps.length?<div className="laps-table"><table><thead><tr><th>Tour</th><th>Durée</th><th>Distance</th><th>FC moyenne</th></tr></thead><tbody>{detail.laps.map((lap,i)=><tr key={i}><td>{lap.lapIndex??i+1}</td><td>{duration(lap.duration)}</td><td>{distance(lap.distance,s)}</td><td>{lap.averageHR==null?'—':`${number(lap.averageHR)} bpm`}</td></tr>)}</tbody></table></div>:<p className="hint">{detail?.fetched_at?'Aucun tour fourni pour cette séance.':'Récupère les détails pour consulter les tours disponibles.'}</p>}</article></>:!error&&<p>Chargement de la séance…</p>}</div>;
}
export function GarminSchedule(){
 type Schedule={enabled:boolean;minutes:number;next_run:string|null;error:string|null;deferred?:boolean};
 const [value,setValue]=useState<Schedule|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let live=true;function load(){void request<Schedule>('/garmin/schedule').then(v=>{if(live)setValue(v);}).catch(e=>{if(live)setError(e.message);});}load();const timer=setInterval(load,30000);return()=>{live=false;clearInterval(timer);};},[]);
 async function save(enabled:boolean,minutes:number){setBusy(true);setError('');try{setValue(await request<Schedule>('/garmin/schedule',{method:'PUT',body:JSON.stringify({enabled,minutes})}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <div className="garmin-schedule"><h3>Mise à jour automatique</h3>{error&&<p role="alert" className="error">{error}</p>}{value&&<><label className="memory-toggle"><input type="checkbox" checked={value.enabled} disabled={busy} onChange={e=>void save(e.target.checked,value.minutes)}/>Synchroniser en arrière-plan</label><label>Fréquence<select aria-label="Fréquence de synchronisation Garmin" value={value.minutes} disabled={busy} onChange={e=>void save(value.enabled,Number(e.target.value))}>{[[30,'30 minutes'],[60,'1 heure'],[180,'3 heures'],[360,'6 heures'],[1440,'Chaque jour']].map(([n,label])=><option key={n} value={n}>{label}</option>)}</select></label><p>Après transfert de ta montre vers Garmin Connect, tes nouvelles séances sont récupérées au prochain passage. Les trois derniers jours de santé sont aussi actualisés. Aucun appel IA.</p>{value.error&&<p role="alert" className="error">{value.error} Vérifie Garmin, puis réactive la synchronisation.</p>}{value.deferred?<small>En attente de la fin ou de la reprise de l’import manuel.</small>:value.enabled&&value.next_run&&<small>Prochain passage : {new Date(value.next_run).toLocaleString('fr-FR')}</small>}</>}</div>;
}
